SwingMaster/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='mainpage'),
    path('logout/', views.logout, name='logout'),
]

SwingMaster/mainpage/views.py
from django.shortcuts import render, redirect
from signup.models import User
from analysisresultpage.models import UserScore
from collections import defaultdict

def index(request):
    login_session = request.session.get('login_session', '')

    if login_session == '':
        return redirect('/')
    else:
        name = User.objects.get(user_id=login_session)

        userscore_information = UserScore.objects.all()
        dict = defaultdict(list)
        userscore_dict = defaultdict()
        for i in userscore_information:
            dict[i.userscore_name].append(i.userscore_score)

        for i, v in dict.items():
            userscore_dict[i] = sum(v)/len(v)

        userscore_list = []
        for i, v in userscore_dict.items():
            userscore_list.append([i, v])
        userscore_list.sort(key=lambda x:-x[1])

        ranking = []

        for i in range(11):
            try:
                No = i + 1
                Name = userscore_list[i][0]
                Value = int(userscore_list[i][1])
                ranking.append([No, Name, Value])
            except:
                break

        nickname = name.user_nickname
        userscore_personerl_information = UserScore.objects.filter(userscore_nickname=nickname)

        mytear = 0
        cnt = 0
        for i in range(len(userscore_personerl_information)):
            mytear += userscore_personerl_information[i].userscore_score
            cnt += 1

        try:
            mytear = int(mytear / cnt)
        except:
            pass

        result = {'ranking': ranking, 'name': name, 'mytear': mytear}

        return render(request, 'mainpage_base.html', result)


def logout(request):
    request.session.flush()
    return redirect('/')

SwingMaster/mainpage/templates/mainpage_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes">
    <title>MainPage</title>
    {% block css %}
        <link href="{% static 'css_mainpage_dir/styling_mainpage.css' %}" rel="stylesheet" />
    {% endblock css %}
</head>
<body>
     <div class="entire-box">
        <div class="header">
            {% include 'mainpage_topbar.html' %}
        </div>
        <div class="content">
            {% include 'mainpage_content.html' %}
        </div>
        <div class="footer">
            {% include 'mainpage_footer.html' %}
        </div>
     </div>
</body>
</html>

SwingMaster/mainpage/templates/mainpage_content.html
<div class="rank">
    <img id="main-ranking-img" class="crown" src="../static/assets/img/rank1-1.png">
    <h5>{{ name }}님</h5>
</div>
<table border="1" bordercolor="#E5E4E4" width="300px" height="300px" align="center" frame=void
>
    <th bgcolor="#E5E4E4">No.</th>
    <th bgcolor="#E5E4E4">Name</th>
    <th bgcolor="#E5E4E4">Value</th>
    {% for rank in ranking %}
    <tr>
        {% for i in rank %}
        <td>{{ i }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

<script>
    var img = document.getElementById("main-ranking-img");
    score = "{{ mytear|safe }}";
    score = Number(score)
    if (score >= 90){
        img.src = "../static/assets/img/rank5-1.png";
    }
    else if(score >= 80 & score < 90){
        img.src = "../static/assets/img/rank4-1.png";
    }
    else if(score >= 70 & score < 80){
        img.src = "../static/assets/img/rank3-1.png";
    }
    else if(score >= 60 & score < 70){
        img.src = "../static/assets/img/rank2-1.png";
    }
    else{
        img.src = "../static/assets/img/rank1-1.png";
    }
</script>

SwingMaster/mainpage/templates/mainpage_footer.html
<button class="footer-button" onclick = "location.href = '../camera'" type="button">
    <b style="color:#FFFFFF; font-family:main-font;">분석하기</b>
</button>
<button class="footer-button" onclick = "location.href = '../mypage'" type="button">
    <b style="color:#FFFFFF; font-family:main-font;">마이페이지</b>
</button>
<button class="footer-button" onclick=location.href="{% url 'mainpage:logout' %}" type="button">
    <b style="color:#FFFFFF; font-family:main-font;">로그아웃</b>
</button>

SwingMaster/mainpage/templates/mainpage_topbar.html
<img class="logo" src="../static/assets/img/logo3.png" width="200" height="100">